Repository NationwideTeam/dev-books, pull requests merged in 2022-07, with the labels that each got.

#7 변경 button 컴포넌트
  src/App.jsx
  src/components/buttons/button.css
  src/components/buttons/button.jsx
Labels: component

#9 Feat: 추가 User 컴포넌트
  src/components/User/User.jsx
  src/components/User/user.css
Labels: component

#11 Feat: 추가 tab-menu 컴포넌트
  package-lock.json
  package.json
  src/App.jsx
  src/components/TabMenu/TabMenu.jsx
  src/components/TabMenu/tabMenu.css
Labels: component

#14 Feat: 추가 comment 컴포넌트
  src/components/Comment/Comment.jsx
  src/components/Comment/comment.css
Labels: component

#17 Feat: 추가 email input 컴포넌트
  src/components/TextInput/TextInput.jsx
  src/components/TextInput/textInput.css
Labels: component

#16 Feat: 추가 alert 컴포넌트
  src/components/Alert/Alert.jsx
  src/components/Alert/alert.css
Labels: component

#13 Feat: 추가 top-nav 컴포넌트
  src/assets/icon/icon-arrow-left.svg
  src/assets/icon/icon-more-vertical.svg
  src/assets/icon/icon-search.svg
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/navbar.css
Labels: component

#23 Rename: 변경 button파일명/컴포넌트 경로
  src/components/Navbar/Navbar.jsx
  src/components/buttons/button.jsx
Labels: component

#24 Rename: 변경 button 컴포넌트 파일명
  src/components/buttons/Button.jsx
Labels: component

#31 Feat: 추가 Profile Image Upload 컴포넌트
  src/components/ProfileImgUpload/ProfileImgUpload.jsx
  src/components/ProfileImgUpload/profileImgUpload.css
Labels: component

#34 Feat: 추가 login 페이지 Fix: focus녹색issue
  src/App.jsx
  src/assets/kakaotalk.svg
  src/assets/logoNameEnglish.svg
  src/assets/logoNameKorean.svg
  src/assets/status_bar.svg
  src/components/Buttons/Button.jsx
  src/components/Buttons/button.css
  src/components/Navbar/Navbar.jsx
  src/components/TextInput/TextInput.jsx
  src/components/TextInput/textInput.css
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinMembership/joinMembership.css
  src/pages/Login/Login.jsx
  src/pages/Login/login.css
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/LoginEmail/loginEmail.css
  src/reset.css
Labels: UI

#35 Feat: 추가 content 컴포넌트
  src/components/Content/Content.jsx
  src/components/Content/content.css
Labels: component

#37 Feat: 추가 Profile Update 페이지
  src/pages/ProfileUpdate/ProfileUpdate.jsx
  src/pages/ProfileUpdate/profileUpdate.css
Labels: UI

#39 Feat: 추가 post 페이지
  src/assets/comment-img1.png
  src/assets/comment-img2.png
  src/components/PostComment/postComment.css
  src/pages/SinglePost/SinglePost.jsx
  src/pages/SinglePost/singlePost.css
Labels: UI

#41 Feat: 추가 Product Upload 페이지
  src/pages/ProductUpload/ProductUpload.jsx
  src/pages/ProductUpload/productUpload.css
Labels: UI

#43 Feat: 추가 UserChatList 컴포넌트
  src/components/User/User.jsx
  src/components/User/user.css
Labels: component

#53 Feat: 변경 User 컴포넌트 이미지 props 사용
  src/components/User/User.jsx
Labels: component

#52 Feat: 추가 Join Profile 페이지
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/JoinProfile/joinProfile.css
Labels: UI

#60 Feat: 추가 HomeFeed 페이지
  src/assets/post-img-example2.png
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/HomeFeed/homeFeed.css
Labels: UI

#61 Feat: 추가 ChatFeed 페이지
  src/pages/ChatFeed/ChatFeed.jsx
  src/pages/ChatFeed/chatFeed.css
Labels: UI

#62 Feat: 추가 SearchFeed 페이지
  src/assets/search-img1.png
  src/assets/search-img2.png
  src/pages/SearchFeed/SearchFeed.jsx
  src/pages/SearchFeed/searchFeed.css
Labels: UI

#63 Feat: 추가 NotFound 페이지
  src/pages/NotFound/NotFound.jsx
  src/pages/NotFound/notFound.css
Labels: UI

#48 Feat: 추가 post 업로드하는 페이지
  src/pages/PostUpload/PostUpload.jsx
  src/pages/PostUpload/postUpload.css
Labels: UI

#49 Feat: 추가 post upload 페이지 글,이미지와 함께 구현
  src/assets/icon/icon-x.svg
  src/pages/PostUploadContent/PostUploadContent.css
  src/pages/PostUploadContent/PostUploadContent.jsx
Labels: UI

#64 Feat: 추가 마이프로필/다른사람 프로필 페이지UI/ 추가 ProfileInfo, Products, Postbar 컴포넌트/버튼 포커스 컬러 해결
  src/App.jsx
  src/assets/album1.png
  src/assets/album2.png
  src/assets/album3.png
  src/components/Album/Album.jsx
  src/components/Album/album.css
  src/components/Buttons/button.css
  src/components/Postbar/Postbar.jsx
  src/components/Postbar/postbar.css
  src/components/Products/Products.jsx
  src/components/Products/products.css
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/profileInfo.css
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/myProfile.css
  src/pages/YourProfile/YourProfile.jsx
  src/pages/YourProfile/yourProfile.css
Labels: bug, component, UI

#65 Feat: 추가 chat-room 페이지
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/chatRoom.css
Labels: UI

#66 Feat:추가 splash 페이지
  src/App.jsx
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/SearchFeed/SearchFeed.jsx
  src/pages/Splash/Splash.jsx
Labels: UI

#70 Feat: 추가 Followers 페이지
  src/App.jsx
  src/pages/Followers/Followers.jsx
  src/pages/Followers/followers.css
Labels: UI

#73 Feat: 수정 피드 콘텐츠 보더 속성 삭제
  src/pages/HomeFeed/homeFeed.css
Labels: component

#75 Feat: 수정 label for, input id 속성 추가
  src/components/TextInput/TextInput.jsx
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/ProductUpload/ProductUpload.jsx
  src/pages/ProfileUpdate/ProfileUpdate.jsx
Labels: component, UI

#77 Feat: 추가 뒤로가기 기능
  src/App.jsx
  src/components/Navbar/Navbar.jsx
  src/pages/NotFound/NotFound.jsx
Labels: component

#80 Feat: 추가 이메일 회원가입 기능
  src/components/TextInput/TextInput.jsx
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinMembership/joinMembership.css
Labels: 기능

#82 Feat: 추가 프로필 설정 기능
  src/components/Buttons/Button.jsx
  src/components/ProfileImgUpload/ProfileImgUpload.jsx
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/JoinProfile/joinProfile.css
Labels: 기능

#84 Feat: 추가 로그인기능
  src/pages/LoginEmail/LoginEmail.jsx
Labels: 기능

#88 Fix: 회원가입 / 로그인 예외처리, 이미지 용량 에러 처리, button 비활성화/활성화 기능
  src/components/Buttons/Button.jsx
  src/components/ProfileImgUpload/profileImgUpload.css
  src/components/TextInput/TextInput.jsx
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/JoinProfile/joinProfile.css
  src/pages/LoginEmail/LoginEmail.jsx
Labels: bug, 기능

#99 Feat:추가 Splash 기능
  src/App.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/login.css
  src/pages/Splash/Splash.jsx
  src/pages/Splash/splash.css
Labels: 기능

#100 Feat: 추가 Followings 페이지
  src/App.jsx
  src/pages/Followings/Followings.jsx
  src/pages/Followings/followings.css
Labels: UI

#90 Feat: 추가 읽지않은 메시지 표시 및 채팅방이동
  src/assets/Ellipse 6.svg
  src/components/User/User.jsx
  src/pages/ChatFeed/ChatFeed.jsx
  src/pages/ChatFeed/chatFeed.css
Labels: UI, 기능

#92 Feat: 추가 채팅방 버튼 활성화
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/chatRoom.css
Labels: 기능

#101 Feat: 추가 modal component
  src/components/Modal/Modal.jsx
  src/components/Modal/modal.css
  src/components/ModalContent/ModalContent.jsx
  src/components/ModalContent/modalContent.css
Labels: UI

#106 Feat: 추가 팔로우/언팔로우 버튼 변화 기능
  src/components/Buttons/button.css
  src/pages/YourProfile/YourProfile.jsx
Labels: 기능

#107 Feat: 추가 채팅방 모달창
  src/components/Navbar/Navbar.jsx
  src/pages/ChatRoom/ChatRoom.jsx
  src/pages/ChatRoom/chatRoom.css
Labels: 기능

#109 Feat: 추가 하단탭메뉴 활성화
  src/components/TabMenu/TabMenu.jsx
  src/components/TabMenu/tabMenu.css
Labels: 기능

#112 Feat: 추가 프로필 수정 기능
  src/components/Navbar/Navbar.jsx
  src/pages/ProfileUpdate/ProfileUpdate.jsx
  src/pages/ProfileUpdate/profileUpdate.css
Labels: 기능

#114 Feat: 추가 포스트 이미지 프리뷰 컴포넌트
  src/components/ImgPreview/ImgPreveiw.jsx
Labels: component

#113 Docs: 변경 ProfileInfo 컴포넌트
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/ProfileInfo/profileInfo.css
Labels: component, 기능

#122 Fix: 게시글 등록 기능 - 이미지 URL이 넘어가지 않는 문제
  src/pages/PostUpload/PostUpload.jsx
Labels: bug

#119 Feat: 추가 상품삭제기능
  src/components/Alert/Alert.jsx
  src/components/Alert/alert.css
  src/components/Navbar/Navbar.jsx
  src/components/Products/Products.jsx
  src/components/Products/products.css
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/myProfile.css
Labels: 기능

#120 Docs: 변경 Content 컴포넌트
  src/components/Content/Content.jsx
  src/components/Content/content.css
Labels: component, 기능

#124 Feat: 추가 팔로우/팔로잉 버튼
  src/components/User/User.jsx
  src/components/User/user.css
Labels: 기능

#129 Fix: 수정 포스트 고유 아이디 전달 로직 구현
  src/pages/PostUpload/PostUpload.jsx
Labels: bug

#131 Feat:추가 상품 수정기능
  src/App.jsx
  src/components/Products/Products.jsx
  src/pages/ProductEdit/ProductEdit.jsx
  src/pages/ProductEdit/productEdit.css
Labels: 기능

#132 Feat:수정 myProfile url
  src/pages/MyProfile/MyProfile.jsx
Labels: bug

#133 Fix: Content 컴포넌트 개별 export로 변경
  src/components/Content/Content.jsx
Labels: bug

#135 Fix: 해당 페이지에 적절한 Content 컴포넌트 import
  src/pages/HomeFeed/HomeFeed.jsx
  src/pages/SinglePost/SinglePost.jsx
Labels: bug

#137 Feat: 추가 myProfile 상단 버튼 기능
  src/pages/MyProfile/MyProfile.jsx
Labels: 기능

#142 Feat: 추가 myProfile 판매 중인 상품 섹션 표시 여부
  src/components/Products/Products.jsx
  src/components/Products/products.css
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/myProfile.css
Labels: 기능

#144 Fix: 수정 이미지 2개 이상 업로드 시 문제
  src/components/Content/Content.jsx
  src/pages/SinglePost/SinglePost.jsx
Labels: bug

#147 Fix: 수정 Products 컴포넌트에 props로 accountName 전달 로직 빠짐으로 인한 오류
  src/pages/MyProfile/MyProfile.jsx
Labels: bug

#150 Feat: 추가 댓글 작성 기능
  src/components/Comment/Comment.jsx
  src/components/Comment/comment.css
  src/pages/SinglePost/SinglePost.jsx
  src/pages/SinglePost/singlePost.css
Labels: 기능

#148 Feat: 추가 myProfile 게시글 삭제 및 수정 기능
  src/App.jsx
  src/components/Content/Content.jsx
  src/components/Content/content.css
  src/pages/MyProfile/MyProfile.jsx
  src/pages/PostEdit/PostEdit.jsx
  src/pages/PostEdit/postEdit.css
Labels: 기능

#156 Design: 수정 Splash, Login 페이지 배경 컬러, 로고 위치
  src/pages/Login/Login.jsx
  src/pages/Login/login.css
  src/pages/Splash/Splash.jsx
  src/pages/Splash/splash.css
Labels: Design

#154 Docs: 수정 README 초안 작성
  README.md
Labels: README

#155 Feat: 추가 댓글 불러오기 기능
  src/components/PostComment/PostComment.jsx
  src/components/PostComment/postComment.css
  src/pages/SinglePost/SinglePost.jsx
Labels: 기능

#159 Feat: 추가 myProfile 게시글 섹션 버튼 토글 - 목록형 or 앨범형 표시 기능
  src/components/Album/Album.jsx
  src/components/Album/album.css
  src/components/Postbar/postbar.css
  src/pages/MyProfile/MyProfile.jsx
Labels: 기능

#161 Feat: 추가 youProfile 모달
  src/pages/YourProfile/YourProfile.jsx
  src/pages/YourProfile/yourProfile.css
Labels: 기능

#163 Feat: 추가 홈피드 팔로잉 계정 게시글 보여주는 기능
  src/pages/HomeFeed/HomeFeed.jsx
Labels: 기능

#162 Feat: 추가 게시글 섹션 - 목록형 / 앨범형 버튼 기능
  src/pages/YourProfile/YourProfile.jsx
Labels: 기능

#167 Feat: 추가 댓글 모달
  src/components/PostComment/PostComment.jsx
  src/pages/SinglePost/SinglePost.jsx
  src/pages/SinglePost/singlePost.css
Labels: 기능

#170 Docs: 변경 홈피드 Navbar 검색 아이콘 클릭 시 계정 검색 페이지로 이동
  src/components/Navbar/Navbar.jsx
Labels: 기능

#173 Feat: 추가 게시글의 유저 프로필 이미지 클릭하면 프로필 페이지로 이동
  src/components/Content/Content.jsx
  src/components/Content/content.css
Labels: 기능

#175 Fix: 수정 게시글이나 이미지 둘 중 하나만 작성시 업로드 안되는 문제
  src/pages/PostUpload/PostUpload.jsx
  src/pages/SinglePost/SinglePost.jsx
Labels: bug

#171 Fix: 수정 myProfile, yourProfile 스크롤
  src/pages/MyProfile/MyProfile.jsx
  src/pages/MyProfile/myProfile.css
  src/pages/YourProfile/YourProfile.jsx
  src/pages/YourProfile/yourProfile.css
Labels: bug, UI

#178 Feat: 추가 singlePost페이지 모달창 기능
  src/pages/SinglePost/SinglePost.jsx
Labels: 기능

#181 Feat: 추가 채팅피드 페이지 상단 navBar 버튼 기능
  src/pages/ChatFeed/ChatFeed.jsx
  src/pages/ChatFeed/chatFeed.css
Labels: UI, 기능

#185 Fix: 수정 SearchFeed UI 깨지는 문제
  src/components/User/User.jsx
  src/components/User/user.css
  src/pages/SearchFeed/SearchFeed.jsx
Labels: bug

#183 Fix: 수정 댓글 게시 버튼 활성화 기능 추가
  src/components/Comment/Comment.jsx
  src/components/Comment/comment.css
Labels: 기능

#189 Fix: 수정 게시글 수정 기능 이미지 업로드부분
  src/pages/PostEdit/PostEdit.jsx
Labels: 기능

#191 Feat: 추가 팔로워 수 클릭 시 팔로워 목록 표시
  src/components/ProfileInfo/ProfileInfo.jsx
  src/components/User/User.jsx
  src/components/User/user.css
  src/pages/Followers/Followers.jsx
Labels: 기능

#192 Feat: 추가 팔로잉 수 클릭 시 팔로잉 목록 표시
  src/components/ProfileInfo/ProfileInfo.jsx
  src/pages/Followings/Followings.jsx
Labels: 기능

#193 Fix: 수정 이미지 프리뷰
  src/pages/PostEdit/PostEdit.jsx
Labels: bug

#195 Fix: 수정 댓글 작성 & 게시 후 입력한 댓글 내용이 그대로 남아있는 문제
  src/components/Comment/Comment.jsx
Labels: bug

#198 Feat: 수정 tab-menu css
  src/pages/HomeFeed/homeFeed.css
  src/pages/MyProfile/myProfile.css
Labels: UI

#197 Feat: 추가 YourProfile 내가 팔로우 한 사용자일 경우 언팔로우 버튼 표시
  src/pages/YourProfile/YourProfile.jsx
Labels: 기능

#203 Feat: 추가 팔로워, 팔로잉 목록 - 팔로우 or 취소 버튼 표시
  src/components/Content/Content.jsx
  src/components/User/User.jsx
  src/pages/Followers/Followers.jsx
Labels: UI, 기능

#205 Fix: 수정 팔로워 목록에서 팔로우 → 취소 버튼 변경 불가 현상
  src/components/User/User.jsx
Labels: bug

#207 Feat: 추가 팔로워, 팔로잉 목록에 나의 계정이 표시될 경우 팔로우 버튼 숨김 처리
  src/components/User/User.jsx
Labels: 기능

#210 Fix: 수정 PostUpload페이지에서 이미지 3개 이상 올라가는 이슈
  src/pages/PostUpload/PostUpload.jsx
Labels: bug

#211 Fix: 수정 홈피드에서 게시글 이미지 안보이는 이슈
  src/pages/HomeFeed/HomeFeed.jsx
Labels: bug

#213 Feat: 추가 좋아요 기능
  src/components/Content/Content.jsx
  src/components/Like/Like.jsx
  src/components/Like/like.css
  src/pages/HomeFeed/HomeFeed.jsx
Labels: 기능

#216 Docs: 수정 팔로잉, 팔로워 목록에서 유저 클릭 시 해당 유저의 프로필 페이지로 이동
  src/components/User/User.jsx
Labels: 기능

#218 Feat: 추가 댓글버튼, 이미지&글 클릭하면 해당 게시글의 상세페이지로 이동
  src/components/Content/Content.jsx
  src/components/Content/content.css
  src/pages/HomeFeed/HomeFeed.jsx
Labels: 기능

#219 Feat: 추가 이미지 프리뷰 삭제 기능
  src/components/ImgPreview/ImgPreveiw.jsx
  src/pages/PostEdit/PostEdit.jsx
Labels: 기능

#220 Fix: 수정 #218커밋 머지 후 생긴 컨플릭 수정
  src/components/Content/Content.jsx
Labels: bug

#222 Fix: 수정 댓글 작성할 때 유저 프로필 이미지가 게시글 작성자의 프로필로 보이는 이슈
  src/pages/SinglePost/SinglePost.jsx
Labels: bug

#224 Docs: 수정 프로필 페이지의 게시글 섹션 앨범형에서 이미지 클릭 시 해당 게시글로 이동
  src/components/Album/Album.jsx
  src/components/Album/album.css
Labels: 기능

#226 Fix: 수정 포스트 업로드 페이지 업로드 버튼 활성화
  src/pages/PostUpload/PostUpload.jsx
Labels: bug

#227 Fix: 댓글이 작성된 시간을 계산해 보여주는 로직 추가
  src/components/PostComment/PostComment.jsx
Labels: 기능

#229 Fix: 수정 텍스트 수정시 이미지 날라가는 문제 해결
  src/pages/PostEdit/PostEdit.jsx
Labels: bug, 기능

#230 Fix: 수정 팔로워, 팔로잉 페이지에서 팔로우 버튼이 2번 렌더링 되는 현상
  src/components/User/User.jsx
  src/pages/Followers/Followers.jsx
  src/pages/Followings/Followings.jsx
Labels: bug

#232 Fix: 수정 팔로우 버튼 클릭 시 프로필 페이지로 이동하는 현상
  src/components/User/User.jsx
  src/components/User/user.css
Labels: bug

#233 Docs: 수정 README 2차 작성
  README.md
Labels: README

#235 Fix: 수정 MVP 배포용
  src/App.jsx
  src/components/Like/Like.jsx
  src/components/Products/Products.jsx
  src/pages/ChatFeed/ChatFeed.jsx
  src/pages/ChatFeed/chatFeed.css
  src/pages/HomeFeed/homeFeed.css
  src/pages/JoinMembership/JoinMembership.jsx
  src/pages/JoinProfile/JoinProfile.jsx
  src/pages/LoginEmail/LoginEmail.jsx
  src/pages/MyProfile/MyProfile.jsx
  src/pages/PostEdit/PostEdit.jsx
  src/pages/PostUpload/PostUpload.jsx
  src/pages/SearchFeed/searchFeed.css
  src/pages/SinglePost/SinglePost.jsx
Labels: documentation

#241 Docs: 추가 구현한 기능들이 동작하는 gif
  README.md
Labels: documentation

#244 Docs: 추가 코드 수정 후 만든 gif 추가
  README.md
Labels: documentation

#246 Docs: 수정 댓글 등록 시간 코드 수정 후 gif 새로 등록
  README.md
Labels: documentation

#247 Docs: 수정 조수영 기능 구체화
  README.md
Labels: README
